const express = require('express'); 
const bodyParser = require('body-parser'); 
const cors = require('cors');
const { mongoose } = require('./db.js');
var expenseController = require('./controllers/expenseController.js');
var app = express(); 
app.use(bodyParser.json());
app.use(cors({ origin: 'http://localhost:4200' }));
app.listen(3000, () => console.log('app fired up at port 3000 ok')); 
app.use('/expenses', expenseController);